# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1b00d5b7b3276607f69ab07c464c6dad390791467fb4bf6e0463f96033defdc2d86117c82e628c5cd76b62ce6bc883d3d5c28734f1c1f9f5cec08ffe61abbb0

test:
  secret_key_base: 6e8c8f05026a85e507dc967d9b55ad6ebda86d0d2f7e3a6af88cfea415d948d2e6d6caffcd09d56faa3861e81feea4bd15db1181a8abe58a926f3890d04d90d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
